FROM node:22

WORKDIR /frontend

# Copia solo package.json y package-lock.json para instalar dependencias primero
COPY package*.json ./
RUN npm install

# Copia el resto del código
COPY . .

# Expone el puerto de Vite
EXPOSE 5173

# Comando para levantar el dev server
CMD ["npm", "run", "dev"]
