# Dockerfile.dev (backend)
FROM node:22

# Carpeta de trabajo dentro del contenedor
WORKDIR /backend

# Copiar solo package.json y package-lock.json primero
COPY package*.json ./

# Instalar dependencias
RUN npm install
RUN npm install -g nodemon
# Copiar el resto del código
COPY . .

# Exponer el puerto del servidor
EXPOSE 4000

# Comando para nodemon (solo desarrollo)
CMD ["npm", "run", "dev"]
